### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by aledj2** [Clinical-Genomics/chanjo#191]
I have installed a fresh copy of Anaconda python today (Python v2.7.13.final.0, conda version 4.3.25)

I then followed the instructions to install chanjo but when I tried chanjo init I had the following traceback

Traceback (most recent call last):
  File "/home/aled/anaconda2/bin/chanjo", line 11, in <module>
    sys.exit(root())
  File "/home/aled/anaconda2/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aled/anaconda2/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aled/anaconda2/lib/python2.7/site-packages/click/core.py", line 1061, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/aled/anaconda2/lib/python2.7/site-packages/click/core.py", line 1100, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/aled/anaconda2/lib/python2.7/site-packages/chanjo/cli.py", line 39, in get_command
    return commands[name].load()
  File "/home/aled/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/home/aled/anaconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/home/aled/anaconda2/lib/python2.7/site-packages/chanjo/init/cli.py", line 11, in <module>
    from .bootstrap import pull, BED_NAME, DB_NAME
  File "/home/aled/anaconda2/lib/python2.7/site-packages/chanjo/init/bootstrap.py", line 4, in <module>
    from urllib2.request import urlretrieve
ImportError: No module named request

A bit of googling lead me to change line 4 of File "/home/aled/anaconda2/lib/python2.7/site-packages/chanjo/init/bootstrap.py" from:
    from urllib2.request import urlretrieve
to:
    from urllib import urlretrieve

And it now appears to work.

**Comment by aledj2** [comment]
Solution found here: 
https://stackoverflow.com/questions/36781105/import-urllib-request-importerror-no-module-named-request

**Comment by robinandeer** [comment]
Hey @aledj2!

Thanks for your feedback

In the last series of releases (chanjo 4.x) I dropped support for Python 2 which is why this error comes up. I'd love some feedback to what degree Python 2 is still required in the settings chanjo is used 🙂

https://github.com/robinandeer/chanjo/blob/master/setup.py#L123

**Comment by juiceboxjoe** [comment]
Use python3 and change `urllib.request` to `urllib`.

**Comment by edit4ever** [comment]
Go ahead and try to install this update and see if it works:
https://1drv.ms/u/s!AhL4aRs7Xd05i4Q6_ejMVa_lHbPS0Q?e=gsPsmc

Let me know how it goes.  Thanks!
