### ISSUE TITLE
AttributeError: 'scoped_session' object has no attribute 'engine' when trying to visualize report in browser

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/chanjo#232]
To reproduce:
- install the repo in a conda env
- Populate a demo database with data (see [instructions](https://github.com/Clinical-Genomics/chanjo-report/blob/af4990c8e7143545d1c68ec4cac3801204fed359/Makefile#L12) contained in the makefile (just the part starting with chanjo blablabla)

- Note that chanjo itself connects normally and returns data, for instance by running the command: 
```chanjo -d mysql+pymysql://user:password@localhost:3306/chanjo4_demo  db samples```

![image](https://user-images.githubusercontent.com/28093618/124789876-f2dbd800-df4a-11eb-99b2-15fe237f4aa2.png)

- When instead one runs the command to generate a report: 
```chanjo -d mysql+pymysql://user:password@localhost:3306/chanjo4_demo report```

The server starts: 
![image](https://user-images.githubusercontent.com/28093618/124790209-43533580-df4b-11eb-92b0-530236e8cb36.png)

But when one goes to the browser page indicated by the app, it crashed with the following error:
```
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x7fba8cbcfa90 (otid=0x7fba8c936680) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/chanjo_report/server/blueprints/index/views.py", line 16, in index
    sample_objs = api.query(Sample).limit(20)
  File "<string>", line 2, in query
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 23, in _proxied
    return self.registry()
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 155, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/Users/chiararasi/miniconda3/envs/py38/lib/python3.8/site-packages/flask_alchy.py", line 41, in __getattr__
    return getattr(self.session, attr)
AttributeError: 'scoped_session' object has no attribute 'engine'
```

**Comment by northwestwitch** [comment]
Found the reason why it's not working, or at least how to fix it!

If you install the package in a Docker container or a virtualenv, SQLAlchemy==1.4.20 is installed. This is version is NOT working. If you remove SQLAlchemy and instead install SQLAlchemy<1.4 it works again!
