### ISSUE TITLE
maximum recursion depth exceeded when loading a sample

### ISSUE THREAD

**Issue by mhkc** [Clinical-Genomics/chanjo#240]
I get the following stacktrace when I am trying to load a sample into chanjo. The error exist with clinicalgenomics docker container version 4.6 and 4.6.1.

``` sh
Traceback (most recent call last):
  File "/opt/conda/bin/chanjo", line 33, in <module>
    sys.exit(load_entry_point('chanjo', 'console_scripts', 'chanjo')())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/worker/app/chanjo/cli/load.py", line 51, in load
    chanjo_db.add(result.sample)
  File "/opt/conda/lib/python3.7/site-packages/alchy/manager.py", line 69, in add
    self.session.add(instance)
  File "/opt/conda/lib/python3.7/site-packages/alchy/manager.py", line 283, in __getattr__
    return getattr(self.session, attr)
  File "/opt/conda/lib/python3.7/site-packages/alchy/manager.py", line 283, in __getattr__
    return getattr(self.session, attr)
  File "/opt/conda/lib/python3.7/site-packages/alchy/manager.py", line 283, in __getattr__
    return getattr(self.session, attr)
  [Previous line repeated 491 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

The example sample that I am trying to load

```
# chrom chromStart      chromEnd        F3      F4      F5      F6      readCount       meanCoverage    percentage10    percentage15    percentage20    percentage50    percentage100   sampleName
1       11874   12227   1-11874-12227   NR_046018.2     37102   DDX11L1 0       0       0       0       0       0       0       4929-21
1       12613   12721   1-12613-12721   NR_046018.2     37102   DDX11L1 8       2.69444 0       0       0       0       0       4929-21
1       13221   14409   1-13221-14409   NR_046018.2     37102   DDX11L1 170     18.4924 86.1111 66.1616 48.6532 0       0       4929-21
1       14362   14829   1-14362-14829   NR_024540.1     38034   WASH7P  169     44.0514 100     100     100     24.6253 0       4929-21
1       14970   15038   1-14970-15038   NR_024540.1     38034   WASH7P  21      14.3088 100     42.6471 0       0       0       4929-21
1       15796   15947   1-15796-15947   NR_024540.1     38034   WASH7P  80      35.2252 100     100     100     15.2318 0       4929-21
1       16607   16765   1-16607-16765   NR_024540.1     38034   WASH7P  121     34.8861 100     91.1392 54.4304 24.6835 0       4929-21
1       16858   17055   1-16858-17055   NR_024540.1     38034   WASH7P  186     75.0152 100     100     100     78.6802 18.7817 4929-21
1       17233   17368   1-17233-17368   NR_024540.1     38034   WASH7P  183     95.6815 100     100     100     100     7.40741 4929-21
```

#  How to reproduce error

Setup debug environment. The files can be found here [chanjo_error.tar.gz](https://github.com/Clinical-Genomics/chanjo/files/9624564/chanjo_error.tar.gz).

``` sh
docker-compose -f chanjo-compose.yml up -d mariadb
docker-compose -f chanjo-compose.yml run --rm -T chanjo-cli chanjo init
```

Test loading sample

``` sh
docker-compose -f chanjo-compose.yml run --rm -T chanjo-cli chanjo load < chanjo.error
```

**Comment by mhkc** [comment]
I still get the same error after removing the space, `# chrom` -> `#chrom`

**Comment by northwestwitch** [comment]
It shouldn't be the `# chrom` thing, as the demo file provided in the init folder also contain space after #. I'm trying with you example @mhkc but if I copy-paste I lose the tab-separated formatting. I'll fix it and let you know!

**Comment by dnil** [comment]
Here's my log:
```
perl -ne 'chomp; s/\s+/\t/g; print $_, "\n";' testfile > testfile.tabs`
(chanjo-report) MacBook-Pro:chanjo-demo dannil$ chanjo load testfile.tabs 
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/chanjo-report/bin/chanjo", line 8, in <module>
    sys.exit(root())
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/chanjo/cli/load.py", line 44, in load
    result = load_transcripts(bed_stream, sample_id=sample, group_id=group,
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/chanjo/load/sambamba.py", line 26, in load_transcripts
    transcripts = groupby_tx(exons, sambamba=True)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/chanjo/load/utils.py", line 7, in groupby_tx
    for exon in exons:
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/chanjo/load/parse/sambamba.py", line 29, in depth_output
    yield expand_row(header_data, row)
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/chanjo/load/parse/sambamba.py", line 67, in expand_row
    thresholds = {threshold: float(row[key])
  File "/usr/local/miniconda3/envs/chanjo-report/lib/python3.9/site-packages/chanjo/load/parse/sambamba.py", line 67, in <dictcomp>
    thresholds = {threshold: float(row[key])
ValueError: could not convert string to float: '4929-21'
(chanjo-report) MacBook-Pro:chanjo-demo dannil$ nano testfile.tabs 
(chanjo-report) MacBook-Pro:chanjo-demo dannil$ chanjo load testfile.tabs 
loading transcripts  [####################################]  100%
```

**Comment by dnil** [comment]
Oh, I see; the space in the test file is a %20 space, whereas the columns are separated with tabs %09. Ok, that explains that at least. It also wasn't the same error Markus got anyway. Thanks for testing!

**Comment by dnil** [comment]
> > Oh, I see; the space in the chanjo demo file is a %20 space, whereas the columns are separated with tabs %09. Ok, that explains that at least. It also wasn't the same error Markus got anyway. Thanks for testing!
> 
> 
> 
> So if you join # + chrom it works?
> 
> 
> 
> 

Yes, but that only means I couldn't reproduce the container issue on my unholy monster of a current local (migrated conda env to M1 and using a SQLite instead of mariadb).

**Comment by northwestwitch** [comment]
Given a bed file placed in the chanjo root dir, I can reproduce the error by running the following commands:

```
docker-compose build
docker-compose run chanjo-cli /bin/bash -c "chanjo -d mysql+pymysql://chanjoUser:chanjoPassword@mariadb/chanjo4_test init --auto test && chanjo --config test/chanjo.yaml link test/hgnc.grch37p13.exons.bed"
docker-compose run chanjo-cli chanjo --config test/chanjo.yaml load appo.tab
```

**Comment by northwestwitch** [comment]
I think it might be due to missing writing permission of the Docker worker over the app folder, in the container. I'll try a tentative fix!

**Comment by northwestwitch** [comment]
I don't know chanjo very well, so it's an hypothesis.
Could the problem be due to the fact that when you init the database in this step:

> docker-compose -f chanjo-compose.yml run --rm -T chanjo-cli chanjo init

Then **inside the container you are creating files that are required for the other step**, loading the transcripts:

> Test loading sample
> 
> ```shell
> docker-compose -f chanjo-compose.yml run --rm -T chanjo-cli chanjo load < chanjo.error
> ```

**The problem is that if the other step is running in another container, that doesn't have those files.** You are also not providing the specifics of the database to use in the chanjo command?

For testing purposes, you could **modify the docker-compose file by adding a volume**: this way the files created in the first step should be found also in the second step.

Add also the volume where your bed file is, if it's not in the chanjo root folder

<hr>

What if you try this then:
`docker-compose build`

Init the database and create a "temp" folder inside the chanjo root, 

`docker-compose run chanjo-cli /bin/bash -c "chanjo -d mysql+pymysql://chanjoUser:chanjoPassword@mariadb/chanjo4_test init --auto temo && chanjo --config temp/chanjo.yaml link temp/hgnc.grch37p13.exons.bed"
`

where 2 files get saved:
- demo/hgnc.grch37p13.exons.bed
- demo/chanjo.yaml

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/28093618/191930819-27155d3c-5667-4efa-87a2-13932fb22d61.png">

demo/chanjo.yaml contains the database URL, so in the next step you can use this config file instead:

`docker-compose run chanjo-cli chanjo --config test/chanjo.yaml load chanjo/init/demo-files/sample1.coverage.bed`
